server:
  port: 80


spring:
  application:
    #微服务名称
    name: cloud-consumer-order
  #数据库配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    #mysql5.x的没有cj
    driver-class-name: com.mysql.cj.jdbc.Driver
    #记得先创建数据库
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: abc123
  cloud:
    zookeeper:
      connect-string: 192.168.11.144:2181 #虚拟机中Zookeeper服务器的IP和端口号

#mybatis配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.atguigu.springcloud.entities  #所有Entity别名类所在包
